SEPARATOR TAB
COLUMNCOUNTING STRICT
CHROMOSOMELABEL CHR
POSITIONLABEL POS
CUSTOMVARIABLE N
LABEL N as N
TRACKPOSITIONS ON
AVERAGEFREQ ON
MINMAXFREQ ON
ADDFILTER CODE_ALL_FQ >= 0.001
ADDFILTER CODE_ALL_FQ <= 0.999
MARKERLABEL SNPID
ALLELELABELS EFFECT_ALLELE REFERENCE_ALLELE
EFFECTLABEL BETA
PVALUELABEL PVAL
WEIGHTLABEL N
FREQLABEL CODE_ALL_FQ
STDERRLABEL SE
SCHEME STDERR
GENOMICCONTROL OFF
LOGPVALUE ON
OUTFILE /home/jhz22/SomaLogic/METAL/2805-6_2- .tbl
PROCESS /home/jhz22/SomaLogic/sumstats/FHS/FHS.2805-6_2.txt.gz
PROCESS /home/jhz22/SomaLogic/sumstats/KORA/KORA.2805-6_2.txt.gz
PROCESS /home/jhz22/SomaLogic/sumstats/Malmo/Malmo.2805-6_2.txt.gz
PROCESS /home/jhz22/SomaLogic/sumstats/QMDiab/QMDiab.2805-6_2.txt.gz
PROCESS /home/jhz22/SomaLogic/sumstats/TwinsUK/TwinsUK.2805-6_2.txt.gz
ANALYZE HETEROGENEITY
CLEAR
