# 29-3-2020 JHZ

source("test.ini")
filtered <- scan("filtered.list","")
# h5mm()
library(dplyr)
library(Seurat)
id <- filtered[1]
tx.data <- Read10X(id)
tx <- new("seurat", raw.data = tx.data)
tx <- CreateSeuratObject(counts = tx.data, project = "Donor", min.cells = 3, min.features = 200)
tx[["percent.mt"]] <- PercentageFeatureSet(tx, pattern = "^MT-")
VlnPlot(tx, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
plot1 <- FeatureScatter(tx, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(tx, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
tx <- subset(tx, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)
tx <- NormalizeData(tx)
tx <- FindVariableFeatures(tx, selection.method = "vst", nfeatures = 2000)
top10 <- head(VariableFeatures(tx), 10)
plot1 <- VariableFeaturePlot(tx)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
all.genes <- rownames(tx)
tx <- ScaleData(tx, features = all.genes)
tx <- RunPCA(tx, features = VariableFeatures(object = tx))
print(tx[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(tx, dims = 1:2, reduction = "pca")
DimPlot(tx, reduction = "pca")
DimHeatmap(tx, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(tx, dims = 1:15, cells = 500, balanced = TRUE)
tx <- JackStraw(tx, num.replicate = 100)
tx <- ScoreJackStraw(tx, dims = 1:20)
JackStrawPlot(tx, dims = 1:15)
ElbowPlot(tx)
tx <- FindNeighbors(tx, dims = 1:10)
tx <- FindClusters(tx, resolution = 0.5)
tx <- RunUMAP(tx, dims = 1:10)
DimPlot(tx, reduction = "umap")
saveRDS(tx, file = paste0(id,"_test.rds"))
cluster1.markers <- FindMarkers(tx, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers, n = 5)
cluster5.markers <- FindMarkers(tx, ident.1 = 5, ident.2 = c(0, 3), min.pct = 0.25)
head(cluster5.markers, n = 5)
tx.markers <- FindAllMarkers(tx, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
tx.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)
cluster1.markers <- FindMarkers(tx, ident.1 = 0, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE)
VlnPlot(tx, features = c("CCL21", "TFF3"))
VlnPlot(tx, features = c("CCL21", "TFF3"), slot = "counts", log = TRUE)
FeaturePlot(tx, features = c("ACE2","ABO","APOE","CCL21"))
top10 <- tx.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
DoHeatmap(tx, features = top10$gene) + NoLegend()
new.cluster.ids <- c("ACE2", "ABO", "APOE4","CCL21",rownames(tx.data)[1:6])
names(new.cluster.ids) <- levels(tx)
tx <- RenameIdents(tx, new.cluster.ids)
DimPlot(tx, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
saveRDS(tx, file = paste0(id,"_final.rds"))
